version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: 'abobwhite/jenkins-docker:latest'
    ports:
      - '80:8080'
      - '8443:8443'
      - '50000:50000'
    environment:
      - 'JENKINS_USERNAME=admin'
      - 'JENKINS_PASSWORD=your-password-here'
      - 'TZ=America/Chicago'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:
